### PR TITLE
fix: Block descendant focus requests Resolves #55

### LINKED ISSUE #55: 🔥[🐛] Parameter must be descendant of view crash
Code in AdmobBanner view manager potentially causing app crashes, solution may need to be inserted around this line:

https://github.com/invertase/react-native-google-ads/blob/2e5987aee8fa34855c657950ae36323a136b3aae/android/src/main/java/io/invertase/googleads/ReactNativeGoogleAdsBannerAdViewManager.java#L116

See discussion here ( https://github.com/facebook/react-native/issues/32649#issuecomment-990968256 ), where there has been a fix suggested for the firebase/admob 11.5.0 release. Code appears to be the same/similar here, worth adding this fix?

### PR DESCRIPTION
**Pull request by TaylorDale**
See discussion https://github.com/facebook/react-native/issues/32649#issuecomment-990968256

### Checklist

- I read the [Contributor Guide](https://github.com/invertase/react-native-google-ads/blob/main/CONTRIBUTING.md)
  and followed the process outlined there for submitting PRs.
  - [x ] Yes
- My change supports the following platforms;
  - [x ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x ] No

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Thanks for posting this!
This looks good to me and has great support from the links referenced in linked issue. What do you think @dylancom  ?

**Comment by mikehardy** [comment]
Don't worry about the PR title conventional CI action, github treats single commits specially during PR merge, using just the commit title, not the PR title, so if the original commit isn't conventional you can't fix it with the PR. You could fix it with a force push of an edited commit message, but the CI failure will just serve as a maintainer warning during merge to squash-merge and edit the final commit title, and that is also fine.

**Comment by mikehardy** [comment]
bonus, now there are 2 commits, the PR title wins and it's semantic-release/conventional ;-)

**Comment by TaylorDale** [comment]
> bonus, now there are 2 commits, the PR title wins and it's semantic-release/conventional ;-)

See it wasn't just a clumsy commit, it was meant to be!

**Comment by dylancom** [comment]
Looks good to me and has been also approved by other users suggesting a patch :)

**Comment by mikehardy** [comment]
Note to self: the CI checks for things like lint should be integrated locally in a pre-push git hook...

**Pull request merged**
