### PR TITLE
refactor: eliminates require cycles, and some unused code

### LINKED ISSUE #34: [🐛] Require cycle in the lib
I just tried to migrate existing project from `@react-native-firebase/admob@11.5.0` to `@invertase/react-native-google-ads@2.0.0`. Testing it first on Android in dev mode, it seems to fail right away with `admob()` call returning `undefined`. RN logs warn about require cycles, ~and that would be my first guess for the problem~:
image
I'll probably debug further and submit a PR later.

P.S.: Glad to see you finally found time to try to make this lib happen, but imho you should be a bit more modest with bumping the major release version on each change. It would make more sense to keep it 0.x.y until it is really tested and confirmed to work in the field.

P.S.S.: Actually, I figured out that in v2.0.0 the default export is just `googleMobileAds` itself, while according to docs and latest code the function `() => googleModileAds` is exported.

### PR DESCRIPTION
**Pull request by birdofpreyru**
### Description

Presumably, this gets rid of require cycles in the code, and removes a bit of unused code.

### Related issues

Fixes #34 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `__tests__e2e__`
  - [ ] `jest` tests added or updated in `__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-admob` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@mikehardy can you please approve running actual tests on this PR? I was hoping to rapidly check whether my changes work :sweat_smile:

**Review by mikehardy — APPROVED** [review]
interesting - looks very sensible on the repair of require cycle
nice catch purging out some of the firebase stuff held over from previous life in react-native-firebase, and I appreciate the cleaning on the lint
I imagine CI should stay green with it

**Comment by mikehardy** [comment]
on it! :-)

**Comment by mikehardy** [comment]
Ah nope. I'm about to be away from keyboard for a little while but all the CI jobs just do things that run locally, so no need to wait for approval (which is required now to avoid first contributors posting bitcoin miners as PRs, what a world...)

they are all in the package.json as run scripts

**Review by mikehardy — CHANGES_REQUESTED** [review]
just formally noting needs what is likely some trivial attention to get the tests / lint going

**Comment by birdofpreyru** [comment]
Yeah, I just wasn't sure whether all tests in package.json are used or legacy stuff, so wanted to get the first run here to see what is actually used.

**Review by mikehardy — APPROVED** [review]
Still LGTM - but now appears to pass CI - just waiting on the builds - thanks again!

**Pull request merged**
