### PR TITLE
fix(ios): already presenting another view controller

### LINKED ISSUE #47: [🐛] 🔥  IOS [googleAds/unknown error] rewarded ad 'The provided view controller is already presenting another view controller'
## Issue

I'm trying to get rewarded ad on IOS, and after it loaded and invoked with rewarded.show(), I'm getting [googleAds/unknown error] when using real/test unit ids on emulator, and test unit id on a real device, the only exception is when I'm using real unit id on the real device I'm getting [googleAds/no-fill] error on ad load (screens below). On android everything working fine it seems.
Both ios and android devices were added on admob console as test devices.

I used another library with the same unit ids from admob and it worked both for ios and android, but that library didn't provide server-side verification.

**This is effect initializing rewarded ad**

**This is onPress handler**

**IOS console output on emulator**
with test unit id:

with real ios unit id:

**IOS console output on a real device specified as a test device on admob console**
with test unit id:

with real ios unit id:

**Android console output on emulator**
works fine both with test id and real id, and showing an advert

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "samplename",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "adb reverse tcp:8081 tcp:8081 && adb reverse tcp:3001 tcp:3001 && react-native start",
    "start": "react-native start",
    "server": "nodemon babel-node mock_server.js",
    "port": "adb reverse tcp:8081 tcp:8081 && adb reverse tcp:3001 tcp:3001",
    "test": "jest",
    "lint": "eslint .",
    "pod": "npx pod-install",
    "postinstall": "npx jetify"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.1.2",
    "@invertase/react-native-google-ads": "^3.2.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^12.1.0",
    "@react-native-firebase/auth": "^12.1.0",
    "@react-native-google-signin/google-signin": "^6.0.1",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/native": "^6.0.0-next.15",
    "@react-navigation/native-stack": "^6.0.0-next.9",
    "axios": "^0.21.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "qs": "^6.10.1",
    "react": "17.0.1",
    "react-native": "0.64.2",
    "react-native-bootsplash": "^3.2.4",
    "react-native-config": "^1.4.2",
    "react-native-device-info": "^8.1.4",
    "react-native-fbsdk-next": "^4.3.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-get-random-values": "^1.7.0",
    "react-native-localize": "^2.1.1",
    "react-native-material-ripple": "^0.9.1",
    "react-native-modal": "^13.0.0",
    "react-native-paper": "^4.9.2",
    "react-native-payments": "^0.8.4",
    "react-native-reanimated": "^2.2.0",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.4.0",
    "react-native-svg": "^12.1.1",
    "react-native-toast-notifications": "^3.2.3",
    "react-native-vector-icons": "^8.1.0",
    "react-native-video": "^5.2.0",
    "react-redux": "^7.2.4",
    "redux": "^4.1.0",
    "redux-saga": "^1.1.3",
    "uuid": "^8.3.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^7.2.0",
    "eslint-config-airbnb": "18.2.1",
    "eslint-import-resolver-babel-module": "^5.3.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.21.5",
    "eslint-plugin-react-hooks": "^1.7.0",
    "express": "^4.17.1",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "nodemon": "^2.0.12",
    "react-test-renderer": "17.0.1",
    "reactotron-react-native": "^5.0.0",
    "reactotron-redux": "^3.1.3",
    "reactotron-redux-saga": "^4.2.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

#### `app.json`:

```json
{
  "name": "samplename",
  "displayName": "samplename",
  "react-native-google-ads": {
    "android_app_id": "android_unit_id",
    "ios_app_id": "ios_unit_id"
  }
}

```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# inhibit_all_warnings! - ignore all xcode warnings

target 'pro_appetit' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'GoogleSignIn', '~> 5.0.0'

  target 'pro_appetitTests' do
    inherit! :complete
    # Pods for testing
  end


  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
  end
end

```

---
</p>
</details>

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31
        ndkVersion = "20.1.5948944"
        googlePlayServicesAuthVersion = "16.0.1"
    }
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.1.0")
        classpath 'com.google.gms:google-services:4.3.8'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        mavenCentral()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}

```

#### `android/app/build.gradle`:

```groovy
apply plugin: "com.android.application"

import com.android.build.OutputFile


project.ext.react = [
    enableHermes: false,  // clean and rebuild if changing
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"

project.ext.vectoricons = [
    iconFontNames: [ 'MaterialIcons.ttf', 'FontAwesome.ttf', 'MaterialCommunityIcons.ttf' ]
]
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore.
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US.  Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

/**
 * Whether to enable the Hermes VM.
 *
 * This should be set on project.ext.react and mirrored here.  If it is not set
 * on project.ext.react, JavaScript will not be compiled to Hermes Bytecode
 * and the benefits of using Hermes will therefore be sharply reduced.
 */
def enableHermes = project.ext.react.get("enableHermes", false);

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.pro_appetit"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 2
        versionName "1.0"
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }

    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // https://developer.android.com/studio/build/configure-apk-splits.html
            // Example: versionCode 1 will generate 1001 for armeabi-v7a, 1002 for x86, etc.
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a": 3, "x86_64": 4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        defaultConfig.versionCode * 1000 + versionCodes.get(abi)
            }

        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    //noinspection GradleDynamicVersion
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation 'com.google.android.gms:play-services-wallet:17.0.0'
    implementation 'com.android.support:appcompat-v7:24.1.1'

    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.0.0"

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}") {
      exclude group:'com.facebook.fbjni'
    }

    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.facebook.flipper'
    }

    if (enableHermes) {
        def hermesPath = "../../node_modules/hermes-engine/android/";
        debugImplementation files(hermesPath + "hermes-debug.aar")
        releaseImplementation files(hermesPath + "hermes-release.aar")
    } else {
        implementation jscFlavor
    }
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)

apply plugin: "com.google.gms.google-services"

```

#### `android/settings.gradle`:

```groovy
rootProject.name = 'samplename'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```

#### `AndroidManifest.xml`:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.pro_appetit">

    <uses-permission android:name="android.permission.INTERNET" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <meta-data
        android:name="com.google.android.gms.wallet.api.enabled"
        android:value="true" />
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
      </activity>
      <activity
        android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
        android:theme="@style/BootTheme"
        android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
      </activity>
    </application>
</manifest>

```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 11.3
    CPU: (8) arm64 Apple M1
    Memory: 203.09 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.10.0 - /opt/homebrew/bin/npm
    Watchman: 2021.12.06.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 27, 28, 29, 30, 31
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play ARM 64 v8a, android-S | Google Play ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7351085
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
- **Are you using `TypeScript`?**
  - N

</p>
</details>

---

- 👉 Check out [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by dylancom**
### Description

This problem has also already been reported before in the firebase repo: https://github.com/invertase/react-native-firebase/issues/4631

Fixes #47
Inspired by: https://github.com/sbugert/react-native-admob/blob/6eb700310af53b1be276f007537b2d237824f87f/ios/RNAdMobRewarded.m#L82

### CODE REVIEW

**Comment by danilaberentsev** [comment]
@dylancom it's also the same thing for InterstitialAd, just in case

**Comment by dylancom** [comment]
@danilaberentsev hmm I didn't see difference between how we show an interstitial and the lib you said...

**Comment by danilaberentsev** [comment]
> @danilaberentsev hmm I didn't see difference between how we show an interstitial and the lib you said...

if you referencing to https://github.com/react-native-admob/admob then I didn't test interstitials there, I didn't need them in the first place. But tested them here so they give the same error as rewarded if opened in modal

**Comment by dylancom** [comment]
Oke, feel free to submit a PR if you know how to fix this.

**Comment by danilaberentsev** [comment]
sadly I know nothing about swift/objective-c 😅

**Comment by mikehardy** [comment]
Even though objective-C may be my least favorite language ever, and I only use it when I have to for react-native purposes, it's not so bad. You might be surprised if you give it a try. Just try not to spend too much time in Xcode or you'll go crazy ;-)

**Comment by mikehardy** [comment]
@dylancom what's your thinking here? Is this worth salvaging and integrating somehow? I'm a big fan of re-using code that has been proven to work so pulling a working solution from the other lib really is attractive...

**Comment by dylancom** [comment]
I think it’s worth it to do some extra investigation here. I closed this as I haven’t actually tested it and want to first reproduce it myself when I have time. (+ see if the code from the deprecated popular lib makes a difference)
I think we should leave an issue open.

Verstuurd vanaf mijn iPhone

**Comment by hannojg** [comment]
i have this issue, let me test the PRs changes in our app …

**Comment by hannojg** [comment]
Okay, with this change the issue still happens, using react-navigation. Might work with rn modal, not sure. Will look into a solution for react navigation…

**Comment by hannojg** [comment]
Okay, my solution (zero obj-c/ios native experience) looks like this. I am just [going through the UIViewController hierarchy](https://stackoverflow.com/a/21848247/3668241) to find the current view controller (think of react-navigation having a stack):

```objc
- (UIViewController *) getVisibleViewControllerFrom:(UIViewController *) vc {
    if ([vc isKindOfClass:[UINavigationController class]]) {
        return [self getVisibleViewControllerFrom:[((UINavigationController *) vc) visibleViewController]];
    } else if ([vc isKindOfClass:[UITabBarController class]]) {
        return [self getVisibleViewControllerFrom:[((UITabBarController *) vc) selectedViewController]];
    } else {
        if (vc.presentedViewController) {
            return [self getVisibleViewControllerFrom:vc.presentedViewController];
        } else {
            return vc;
        }
    }
}

RCT_EXPORT_METHOD(rewardedShow
                  : (nonnull NSNumber *)requestId
                  : (NSString *)adUnitId
                  : (NSDictionary *)showOptions
                  : (RCTPromiseResolveBlock)resolve
                  : (RCTPromiseRejectBlock)reject) {
  GADRewardedAd *rewardedAd = rewardedMap[requestId];

  if (rewardedAd) {
      UIViewController *controller = [self getVisibleViewControllerFrom:RCTSharedApplication().delegate.window.rootViewController];
    [rewardedAd
        presentFromRootViewController:controller
```

**Pull request closed without merging**
